name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - 'refactor'
      - 'mypy'
      - 'Pyinstaller'
      - 'PyPi'
  - title: '🧔🏽 User Facing'
    labels:
      - 'GUI'
      - 'TUI'
      - 'output data'
      - 'docs'
      - 'source code'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  # Installation/Usage Instructions

  ## tl;dr:
  **Windows Users**

  Grab the file below.

  **Linux users**

  use [PyPi](https://eldonationtracker.readthedocs.io/en/latest/installation.html#via-pypi) or [git clone](https://eldonationtracker.readthedocs.io/en/latest/installation.html#via-github)

  **Docker or Podman users**

  docker run -it -v ./extralifedonationtracker:/root/.config/extralifedonationtracker -v ./testoutput:/root/output djotaku/eldonationtracker:latest
  or
  podman run -it -v ./extralifedonationtracker:/root/.config/extralifedonationtracker:Z -v ./testoutput:/root/output:Z djotaku/eldonationtracker:latest

  ## For more detailed instructions

  Installation Instructions: https://eldonationtracker.readthedocs.io/en/latest/installation.html

  Usage Instructions: https://eldonationtracker.readthedocs.io/en/latest/usage.html

  Please file any bug reports. Pull requests welcome on the devel branch.

  
  ## Changes

  $CHANGES
