# Form implementation generated from reading ui file 'logs.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form:
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(740, 777)
        self.copy = QtWidgets.QPushButton(parent=Form)
        self.copy.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.copy.setObjectName("copy")
        self.logs = QtWidgets.QTextBrowser(parent=Form)
        self.logs.setGeometry(QtCore.QRect(10, 50, 721, 721))
        self.logs.setObjectName("logs")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.copy.setText(_translate("Form", "Copy to Clipboard"))
