# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTdesignerfiles/logs.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(740, 777)
        self.copy = QtWidgets.QPushButton(Form)
        self.copy.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.copy.setObjectName("copy")
        self.logs = QtWidgets.QTextBrowser(Form)
        self.logs.setGeometry(QtCore.QRect(10, 50, 721, 721))
        self.logs.setObjectName("logs")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.copy.setText(_translate("Form", "Copy to Clipboard"))
