# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 729)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.SettingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.SettingsButton.setGeometry(QtCore.QRect(10, 10, 191, 41))
        self.SettingsButton.setAutoDefault(False)
        self.SettingsButton.setDefault(False)
        self.SettingsButton.setFlat(False)
        self.SettingsButton.setObjectName("SettingsButton")
        self.TrackerButton = QtWidgets.QPushButton(self.centralwidget)
        self.TrackerButton.setGeometry(QtCore.QRect(210, 10, 261, 41))
        self.TrackerButton.setObjectName("TrackerButton")
        self.ParticipantInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.ParticipantInfo.setGeometry(QtCore.QRect(10, 60, 301, 271))
        self.ParticipantInfo.setObjectName("ParticipantInfo")
        self.label_4 = QtWidgets.QLabel(self.ParticipantInfo)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.ParticipantInfo)
        self.label_5.setGeometry(QtCore.QRect(140, 30, 121, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.ParticipantInfo)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 56, 15))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.ParticipantInfo)
        self.label_7.setGeometry(QtCore.QRect(150, 130, 111, 16))
        self.label_7.setObjectName("label_7")
        self.TotalRaised = QtWidgets.QTextBrowser(self.ParticipantInfo)
        self.TotalRaised.setGeometry(QtCore.QRect(10, 60, 71, 41))
        self.TotalRaised.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TotalRaised.setObjectName("TotalRaised")
        self.TotalNumDonations = QtWidgets.QTextBrowser(self.ParticipantInfo)
        self.TotalNumDonations.setGeometry(QtCore.QRect(150, 60, 71, 41))
        self.TotalNumDonations.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TotalNumDonations.setObjectName("TotalNumDonations")
        self.Goal = QtWidgets.QTextBrowser(self.ParticipantInfo)
        self.Goal.setGeometry(QtCore.QRect(10, 150, 71, 41))
        self.Goal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Goal.setObjectName("Goal")
        self.AvgDonation = QtWidgets.QTextBrowser(self.ParticipantInfo)
        self.AvgDonation.setGeometry(QtCore.QRect(150, 150, 91, 41))
        self.AvgDonation.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AvgDonation.setObjectName("AvgDonation")
        self.DonationInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.DonationInfo.setGeometry(QtCore.QRect(330, 60, 451, 271))
        self.DonationInfo.setObjectName("DonationInfo")
        self.label = QtWidgets.QLabel(self.DonationInfo)
        self.label.setGeometry(QtCore.QRect(30, 140, 121, 16))
        self.label.setObjectName("label")
        self.RecentDonations = QtWidgets.QTextBrowser(self.DonationInfo)
        self.RecentDonations.setGeometry(QtCore.QRect(10, 160, 431, 101))
        self.RecentDonations.setAutoFillBackground(False)
        self.RecentDonations.setDocumentTitle("")
        self.RecentDonations.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.RecentDonations.setObjectName("RecentDonations")
        self.LastDonation = QtWidgets.QTextBrowser(self.DonationInfo)
        self.LastDonation.setGeometry(QtCore.QRect(10, 40, 431, 31))
        self.LastDonation.setAutoFillBackground(False)
        self.LastDonation.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LastDonation.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LastDonation.setObjectName("LastDonation")
        self.label_2 = QtWidgets.QLabel(self.DonationInfo)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.DonationInfo)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_3.setObjectName("label_3")
        self.TopDonation = QtWidgets.QTextBrowser(self.DonationInfo)
        self.TopDonation.setGeometry(QtCore.QRect(10, 100, 431, 31))
        self.TopDonation.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TopDonation.setObjectName("TopDonation")
        self.ProgressBarButton = QtWidgets.QPushButton(self.centralwidget)
        self.ProgressBarButton.setGeometry(QtCore.QRect(480, 10, 91, 41))
        self.ProgressBarButton.setObjectName("ProgressBarButton")
        self.RefreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.RefreshButton.setGeometry(QtCore.QRect(580, 10, 101, 41))
        self.RefreshButton.setObjectName("RefreshButton")
        self.TestAlertButton = QtWidgets.QPushButton(self.centralwidget)
        self.TestAlertButton.setGeometry(QtCore.QRect(690, 10, 84, 41))
        self.TestAlertButton.setObjectName("TestAlertButton")
        self.TeamGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.TeamGroupBox.setGeometry(QtCore.QRect(10, 340, 771, 291))
        self.TeamGroupBox.setObjectName("TeamGroupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.TeamGroupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 751, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_TeamGoal = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_TeamGoal.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_TeamGoal.setObjectName("label_TeamGoal")
        self.gridLayout_2.addWidget(self.label_TeamGoal, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(254, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 4, 1, 1)
        self.label_TeamCaptain = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_TeamCaptain.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_TeamCaptain.setObjectName("label_TeamCaptain")
        self.gridLayout_2.addWidget(self.label_TeamCaptain, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_TeamTotalRaised = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_TeamTotalRaised.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_TeamTotalRaised.setObjectName("label_TeamTotalRaised")
        self.gridLayout_2.addWidget(self.label_TeamTotalRaised, 1, 4, 1, 1)
        self.label_TopTeamParticipant = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_TopTeamParticipant.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_TopTeamParticipant.setObjectName("label_TopTeamParticipant")
        self.gridLayout_2.addWidget(self.label_TopTeamParticipant, 3, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        self.label_TeamNumDonations = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_TeamNumDonations.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_TeamNumDonations.setObjectName("label_TeamNumDonations")
        self.gridLayout_2.addWidget(self.label_TeamNumDonations, 1, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(62, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.textBrowser_TeamTop5 = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.textBrowser_TeamTop5.setObjectName("textBrowser_TeamTop5")
        self.gridLayout_2.addWidget(self.textBrowser_TeamTop5, 3, 2, 1, 4)
        self.pushButtonRun = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRun.setGeometry(QtCore.QRect(570, 640, 84, 31))
        self.pushButtonRun.setObjectName("pushButtonRun")
        self.pushButtonStop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStop.setGeometry(QtCore.QRect(670, 640, 84, 31))
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.CopyrightLabel = QtWidgets.QLabel(self.centralwidget)
        self.CopyrightLabel.setGeometry(QtCore.QRect(30, 650, 481, 31))
        self.CopyrightLabel.setObjectName("CopyrightLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionCheck_for_Update = QtWidgets.QAction(MainWindow)
        self.actionCheck_for_Update.setObjectName("actionCheck_for_Update")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionCheck_for_Update)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Extra Life Donation Tracker"))
        self.SettingsButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Change folders, Extra Life ID, etc</p></body></html>"))
        self.SettingsButton.setText(_translate("MainWindow", "Settings"))
        self.TrackerButton.setText(_translate("MainWindow", "Tracker"))
        self.ParticipantInfo.setTitle(_translate("MainWindow", "Participant Info"))
        self.label_4.setText(_translate("MainWindow", "Total Raised"))
        self.label_5.setText(_translate("MainWindow", "Total # of Donations"))
        self.label_6.setText(_translate("MainWindow", "Goal"))
        self.label_7.setText(_translate("MainWindow", "Average Donation"))
        self.DonationInfo.setTitle(_translate("MainWindow", "Participant Donation Info"))
        self.label.setText(_translate("MainWindow", "Recent Donations"))
        self.RecentDonations.setPlaceholderText(_translate("MainWindow", "Recent Donations"))
        self.LastDonation.setPlaceholderText(_translate("MainWindow", "Last Donation"))
        self.label_2.setText(_translate("MainWindow", "Last Donation"))
        self.label_3.setText(_translate("MainWindow", "Top Donor"))
        self.TopDonation.setPlaceholderText(_translate("MainWindow", "Top Donor"))
        self.ProgressBarButton.setText(_translate("MainWindow", "Progress Bar"))
        self.RefreshButton.setText(_translate("MainWindow", "Force Refresh"))
        self.TestAlertButton.setText(_translate("MainWindow", "Test Alert"))
        self.TeamGroupBox.setTitle(_translate("MainWindow", "Team Info"))
        self.label_9.setText(_translate("MainWindow", "Team Captain"))
        self.label_TeamGoal.setText(_translate("MainWindow", "Team Goal"))
        self.label_13.setText(_translate("MainWindow", "Top Team Participant"))
        self.label_14.setText(_translate("MainWindow", "Top 5 Team Participants"))
        self.label_TeamCaptain.setText(_translate("MainWindow", "Team Captain"))
        self.label_10.setText(_translate("MainWindow", "Goal"))
        self.label_TeamTotalRaised.setText(_translate("MainWindow", "Raised"))
        self.label_TopTeamParticipant.setText(_translate("MainWindow", "Top Team Participant"))
        self.label_TeamNumDonations.setText(_translate("MainWindow", "# Donations"))
        self.label_12.setText(_translate("MainWindow", "Total Raised"))
        self.label_11.setText(_translate("MainWindow", "# of Donations"))
        self.pushButtonRun.setText(_translate("MainWindow", "Run"))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop"))
        self.CopyrightLabel.setText(_translate("MainWindow", "(C) 2015-2019 Eric Mesa; Licensed GPLv3; http://extralife.ericmesa.com"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionDocumentation.setToolTip(_translate("MainWindow", "Open Documentation in your default browser"))
        self.actionCheck_for_Update.setText(_translate("MainWindow", "Check for Update"))
        self.actionCheck_for_Update.setToolTip(_translate("MainWindow", "Checks for Updates"))
        self.actionAbout.setText(_translate("MainWindow", "About ELDonationTracker"))
