# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTdesignerfiles/settings.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(805, 392)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("QTdesignerfiles/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 791, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.pushButtonSelectFolder = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonSelectFolder.setToolTip("")
        self.pushButtonSelectFolder.setObjectName("pushButtonSelectFolder")
        self.gridLayout.addWidget(self.pushButtonSelectFolder, 1, 3, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditTeamID = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTeamID.setObjectName("lineEditTeamID")
        self.gridLayout.addWidget(self.lineEditTeamID, 3, 1, 1, 1)
        self.label_tracker_image = QtWidgets.QLabel(self.layoutWidget)
        self.label_tracker_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tracker_image.setObjectName("label_tracker_image")
        self.gridLayout.addWidget(self.label_tracker_image, 5, 1, 1, 1)
        self.lineEditParticipantID = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditParticipantID.setToolTip("")
        self.lineEditParticipantID.setToolTipDuration(5)
        self.lineEditParticipantID.setObjectName("lineEditParticipantID")
        self.gridLayout.addWidget(self.lineEditParticipantID, 0, 1, 1, 1)
        self.pushButton_persistentsave = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_persistentsave.setObjectName("pushButton_persistentsave")
        self.gridLayout.addWidget(self.pushButton_persistentsave, 11, 2, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_font = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_font.setObjectName("pushButton_font")
        self.horizontalLayout_2.addWidget(self.pushButton_font)
        self.pushButton_font_color = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_font_color.setObjectName("pushButton_font_color")
        self.horizontalLayout_2.addWidget(self.pushButton_font_color)
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 1, 1, 1)
        self.lineEditCurrencySymbol = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditCurrencySymbol.setObjectName("lineEditCurrencySymbol")
        self.gridLayout.addWidget(self.lineEditCurrencySymbol, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.labelTextFolder = QtWidgets.QLabel(self.layoutWidget)
        self.labelTextFolder.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTextFolder.setObjectName("labelTextFolder")
        self.gridLayout.addWidget(self.labelTextFolder, 1, 1, 1, 2)
        self.pushButton_tracker_background = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_tracker_background.setObjectName("pushButton_tracker_background")
        self.gridLayout.addWidget(self.pushButton_tracker_background, 9, 1, 1, 1)
        self.label_sound = QtWidgets.QLabel(self.layoutWidget)
        self.label_sound.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sound.setObjectName("label_sound")
        self.gridLayout.addWidget(self.label_sound, 6, 1, 1, 1)
        self.label_donors_to_display = QtWidgets.QLabel(self.layoutWidget)
        self.label_donors_to_display.setObjectName("label_donors_to_display")
        self.gridLayout.addWidget(self.label_donors_to_display, 4, 0, 1, 1)
        self.spinBox_DonorsToDisplay = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_DonorsToDisplay.setObjectName("spinBox_DonorsToDisplay")
        self.gridLayout.addWidget(self.spinBox_DonorsToDisplay, 4, 1, 1, 1)
        self.pushButton_tracker_image = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_tracker_image.setObjectName("pushButton_tracker_image")
        self.gridLayout.addWidget(self.pushButton_tracker_image, 5, 2, 1, 1)
        self.pushButton_sound = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_sound.setObjectName("pushButton_sound")
        self.gridLayout.addWidget(self.pushButton_sound, 6, 2, 1, 1)
        self.pushButton_grab_image = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_grab_image.setObjectName("pushButton_grab_image")
        self.gridLayout.addWidget(self.pushButton_grab_image, 5, 4, 1, 1)
        self.pushButton_grab_sound = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_grab_sound.setObjectName("pushButton_grab_sound")
        self.gridLayout.addWidget(self.pushButton_grab_sound, 6, 4, 1, 1)
        self.pushButton_validate_participant_id = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_validate_participant_id.setObjectName("pushButton_validate_participant_id")
        self.gridLayout.addWidget(self.pushButton_validate_participant_id, 0, 2, 1, 1)
        self.pushButton_validate_team_id = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_validate_team_id.setObjectName("pushButton_validate_team_id")
        self.gridLayout.addWidget(self.pushButton_validate_team_id, 3, 2, 1, 1)
        self.pushButtonRevert = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonRevert.setObjectName("pushButtonRevert")
        self.gridLayout.addWidget(self.pushButtonRevert, 10, 2, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings"))
        self.label_6.setText(_translate("Dialog", "Donation Sound"))
        self.pushButtonSelectFolder.setText(_translate("Dialog", "select Folder"))
        self.label_4.setText(_translate("Dialog", "Team ID"))
        self.label_2.setText(_translate("Dialog", "Text Folder"))
        self.label_tracker_image.setText(_translate("Dialog", "No Image Selected"))
        self.pushButton_persistentsave.setStatusTip(_translate("Dialog", "To have the settings persist across upgrades"))
        self.pushButton_persistentsave.setText(_translate("Dialog", "Save"))
        self.label_3.setText(_translate("Dialog", "Currency Symbol"))
        self.label_5.setText(_translate("Dialog", "Tracker Image"))
        self.pushButton_font.setText(_translate("Dialog", "Tracker Font"))
        self.pushButton_font_color.setText(_translate("Dialog", "Tracker Font Color"))
        self.label.setText(_translate("Dialog", "Participant ID"))
        self.labelTextFolder.setText(_translate("Dialog", "No Folder Selected"))
        self.pushButton_tracker_background.setText(_translate("Dialog", "Change Tracker Background Color"))
        self.label_sound.setText(_translate("Dialog", "No Sound Selected"))
        self.label_donors_to_display.setText(_translate("Dialog", "Donors to Display"))
        self.pushButton_tracker_image.setText(_translate("Dialog", "select Image"))
        self.pushButton_sound.setText(_translate("Dialog", "select Sound"))
        self.pushButton_grab_image.setText(_translate("Dialog", "Grab from Github"))
        self.pushButton_grab_sound.setText(_translate("Dialog", "Grab from Github"))
        self.pushButton_validate_participant_id.setText(_translate("Dialog", "Validate Participant ID"))
        self.pushButton_validate_team_id.setText(_translate("Dialog", "Validate Team ID"))
        self.pushButtonRevert.setText(_translate("Dialog", "Revert"))
