name: Windows_Build

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 extralifedonations.py IPC.py readparticipantconf.py team.py donation.py donor.py extralife_IO.py  --count --select=E9,F63,F7,F82 --show-source --statistics 
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 extralifedonations.py IPC.py readparticipantconf.py team.py donation.py donor.py extralife_IO.py  --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 
    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests/test.py
    - name: Build with Pyinstaller
      run: |
        pip install pyinstaller
        pyinstaller gui.py
        cp participant.conf dist/gui/
        cp Engineer.png dist/gui
        cp Donation.mp3 dist/gui
        cp icon.png dist/gui
        cp dist/gui/Qt5Core.dll dist/gui/PyQt5/Qt/bin
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: Windows-Build
        path: dist/gui
