name: Windows Build

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set PATH
      run: |
        echo "D:\\a\\ELDonationTracker\\ELDonationTracker\\ffmpeg" >> $GITHUB_PATH
    - name: Build Single Executable with Pyinstaller
      run: |
        echo "$GITHUB_PATH"
        pip install pyinstaller
        pyinstaller -F -p eldonationtracker -n "eldonationtracker" --icon=icon.ico --add-data="eldonationtracker/icon.png;." eldonationtracker/gui.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: eldonationtracker for Windows
        path: dist/
