name: Windows Build

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.13.3
      uses: actions/setup-python@v6.2.0
      with:
        python-version: 3.13.3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Single Executable with pyside6-deploy
      uses: Nuitka/Nuitka-Action@main
      with:
          nuitka-version: main
          script-name: eldonationtracker/gui.py
          mode: standalone
          output-file: eldonationtracker.exe
          windows-icon-from-ico: icon.ico
          enable-plugins: pyside6
          static-libpython: true
    - name: Upload artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: eldonationtracker for Windows
        path: build\gui.dist\eldonationtracker.exe
        include-hidden-files: true
