name: Windows Build

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 eldonationtracker/participant.py eldonationtracker/ipc.py eldonationtracker/team.py eldonationtracker/donation.py eldonationtracker/donor.py eldonationtracker/extralife_io.py  --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 eldonationtracker/participant.py eldonationtracker/ipc.py eldonationtracker/team.py eldonationtracker/donation.py eldonationtracker/donor.py eldonationtracker/extralife_io.py  --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest 
        pytest -v --pyargs eldonationtracker
    - name: Build Single Executable with Pyinstaller
      run: |
        pip install pyinstaller
        pyinstaller -F -p eldonationtracker -n "eldonationtracker" --icon=icon.ico --add-data="eldonationtracker/icon.png;." eldonationtracker/gui.py
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: eldonationtracker for Windows
        path: dist/
    - name: Build Folder with Pyinstaller
      run: |
        pip install pyinstaller
        pyinstaller -p eldonationtracker eldonationtracker/gui.py
        cp participant.conf dist/gui
        cp icon.png dist/gui
        cp dist/gui/Qt5Core.dll dist/gui/PyQt5/Qt/bin
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Extra Life Donation Tracker for Windows
        path: dist/gui