name: Windows Build

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6.0.2
    - name: Set up Python 3.14
      uses: actions/setup-python@v6.2.0
      with:
        python-version: 3.14
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Single Executable with nuitka action
      uses: Nuitka/Nuitka-Action@main
      with:
          nuitka-version: main
          script-name: src/eldonationtracker/gui.py
          mode: onefile
          output-file: eldonationtracker.exe
          windows-icon-from-ico: icon.ico
          enable-plugins: pyside6
          include-qt-plugins: multimedia
          # static-libpython: yes
    - name: Upload artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: eldonationtracker for Windows
        path: build\eldonationtracker.exe
        include-hidden-files: true
