name: Windows Build

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.3
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyside6
    - name: Build Single Executable with pyside6-deploy
      shell: pwsh
      run: |
        pyside6-deploy -f --name "eldonationtracker" eldonationtracker/gui.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: eldonationtracker for Windows
        path: dist/
